### ISSUE TITLE
python make.py - OSX

### ISSUE THREAD

**Issue by lukleh** [cyberegoorg/cetech#112]
```
Runing genie.
Building configurations...
Running action 'gmake'...
Generating ../.build/projects/gmake-osx/Makefile...
Generating ../.build/projects/gmake-osx/celib_static.make...
Generating ../.build/projects/gmake-osx/cetech1.make...
Done.
Building.
==== Building celib_static (debug32) ====
Creating ../../osx32_clang/bin
Creating ../../osx32_clang/obj/x32/Debug/celib_static
Creating ../../osx32_clang/obj/x32/Debug/celib_static/engine/src/celib/command_line
Creating ../../osx32_clang/obj/x32/Debug/celib_static/engine/src/celib/memory
command_line.cc
memory.cc
../../../engine/src/celib/command_line/command_line.cc:33:71: fatal error: use of undeclared identifier 'nullptr'
            return idx < internal::_argc ? internal::_argv[idx + 1] : nullptr;
                                                                      ^
1 error generated.
make[1]: *** [../../osx32_clang/obj/x32/Debug/celib_static/engine/src/celib/command_line/command_line.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../../../engine/src/celib/memory/memory.cc:2:
../../../engine/src/celib/memory/memory.h:82:41: warning: variadic templates are a C++11 extension
      [-Wc++11-extensions]
        template < typename T, typename ... ARGS >
                                        ^
../../../engine/src/celib/memory/memory.h:86:72: fatal error: 'T' does not refer to a value
            T* mem = (T*) allocator.allocate(sizeof(T) * size, alignof(T));
                                                                       ^
../../../engine/src/celib/memory/memory.h:82:29: note: declared here
        template < typename T, typename ... ARGS >
                            ^
1 warning and 1 error generated.
make[1]: *** [../../osx32_clang/obj/x32/Debug/celib_static/engine/src/celib/memory/memory.o] Error 1
make: *** [celib_static] Error 2
Traceback (most recent call last):
  File "make.py", line 174, in <module>
    main()
  File "make.py", line 163, in main
    make(args.config, args.platform, args.generate)
  File "make.py", line 144, in make
    subprocess.check_call(PLATFORMS_BUILD[platform][config])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', '-R', '-C', '.build/projects/gmake-osx', 'config=debug32']' returned non-zero exit status 2
```

**Comment by lukleh** [comment]
```
Runing genie.
darwin64
Building configurations...
Running action 'gmake'...
Generating ../.build/projects/gmake-osx/Makefile...
Generating ../.build/projects/gmake-osx/celib_static.make...
Generating ../.build/projects/gmake-osx/cetech1.make...
Done.
Building.
==== Building celib_static (debug64) ====
==== Building cetech1 (debug64) ====
main.cc
application.cc
cvar.cc
cvars.cc
In file included from ../../../engine/src/cetech/main.cc:8:
In file included from ../../../engine/src/cetech/application/application.h:7:
In file included from ../../../engine/src/cetech/develop/develop_manager.h:8:
../../../engine/src/celib/time.h:15:27: fatal error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
            clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &temp);
                          ^
In file included from ../../../engine/src/cetech/application/private/application.cc:1:
In file included from ../../../engine/src/cetech/application/application.h:7:
In file included from ../../../engine/src/cetech/develop/develop_manager.h:8:
../../../engine/src/celib/time.h:15:27: fatal error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
            clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &temp);
                          ^
console_server.cc
develop_manager.cc
1 error generated.
make[1]: *** [../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
1 error generated.
make[1]: *** [../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/application/private/application.o] Error 1
In file included from ../../../engine/src/cetech/develop/private/console_server.cc:11:
In file included from ../../../engine/src/cetech/application/application.h:7:
In file included from ../../../engine/src/cetech/develop/develop_manager.h:8:
../../../engine/src/celib/time.h:15:27: fatal error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
            clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &temp);
                          ^
In file included from ../../../engine/src/cetech/develop/private/develop_manager.cc:5:
In file included from ../../../engine/src/cetech/develop/develop_manager.h:8:
../../../engine/src/celib/time.h:15:27: fatal error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
            clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &temp);
                          ^
1 error generated.
make[1]: *** [../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/develop/private/console_server.o] Error 1
1 error generated.
make[1]: *** [../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/develop/private/develop_manager.o] Error 1
make: *** [cetech1] Error 2
Traceback (most recent call last):
  File "make.py", line 174, in <module>
    main()
  File "make.py", line 163, in main
    make(args.config, args.platform, args.generate)
  File "make.py", line 144, in make
    subprocess.check_call(PLATFORMS_BUILD[platform][config])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', '-R', '-C', '.build/projects/gmake-osx', 'config=debug64']' returned non-zero exit status 2
```

**Comment by lukleh** [comment]
```
clang --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by lukleh** [comment]
```
Runing genie.
darwin64
Building configurations...
Running action 'gmake'...
Generating ../.build/projects/gmake-osx/Makefile...
Generating ../.build/projects/gmake-osx/celib_static.make...
Generating ../.build/projects/gmake-osx/cetech1.make...
Done.
Building.
==== Building celib_static (debug64) ====
memory.cc
Archiving celib_static
==== Building cetech1 (debug64) ====
main.cc
application.cc
cvar.cc
cvars.cc
console_server.cc
develop_manager.cc
../../../engine/src/cetech/application/private/application.cc:177:41: warning: unused parameter 'data'
      [-Wunused-parameter]
        static void process_mouse(void* data) {
                                        ^
../../../engine/src/cetech/application/private/application.cc:182:44: warning: unused parameter 'data'
      [-Wunused-parameter]
        static void process_keyboard(void* data) {
                                           ^
../../../engine/src/cetech/application/private/application.cc:187:47: warning: unused parameter 'data'
      [-Wunused-parameter]
        static void console_server_tick(void* data) {
                                              ^
../../../engine/src/cetech/application/private/application.cc:191:38: warning: unused parameter '_data'
      [-Wunused-parameter]
        static void frame_tick(void* _data) {
                                     ^
../../../engine/src/cetech/application/private/application.cc:272:26: warning: declaration shadows a local variable
      [-Wshadow]
                    auto time = develop_manager::enter_scope("Game::Update()");
                         ^
../../../engine/src/cetech/application/private/application.cc:244:22: note: previous declaration is here
                auto time = develop_manager::enter_scope("Application::Update()");
                     ^
../../../engine/src/cetech/application/private/application.cc:177:21: warning: unused function 'process_mouse'
      [-Wunused-function]
        static void process_mouse(void* data) {
                    ^
../../../engine/src/cetech/application/private/application.cc:182:21: warning: unused function 'process_keyboard'
      [-Wunused-function]
        static void process_keyboard(void* data) {
                    ^
../../../engine/src/cetech/application/private/application.cc:187:21: warning: unused function 'console_server_tick'
      [-Wunused-function]
        static void console_server_tick(void* data) {
                    ^
../../../engine/src/cetech/application/private/application.cc:191:21: warning: unused function 'frame_tick'
      [-Wunused-function]
        static void frame_tick(void* _data) {
                    ^
9 warnings generated.
filesystem.cc
../../../engine/src/cetech/develop/private/develop_manager.cc:160:49: warning: unused parameter 'name'
      [-Wunused-parameter]
        time::PerfTimer enter_scope(const char* name) {
                                                ^
../../../engine/src/cetech/develop/private/develop_manager.cc:193:49: warning: unused parameter 'data'
      [-Wunused-parameter]
        static void flush_develop_manager(void* data) {
                                                ^
../../../engine/src/cetech/develop/private/develop_manager.cc:197:48: warning: unused parameter 'data'
      [-Wunused-parameter]
        static void send_develop_manager(void* data) {
                                               ^
../../../engine/src/cetech/filesystem/private/filesystem.cc:257:34: warning: unused parameter 'root'
      [-Wunused-parameter]
        bool exists(StringId64_t root,
                                 ^
../../../engine/src/cetech/filesystem/private/filesystem.cc:263:40: warning: unused parameter 'root'
      [-Wunused-parameter]
        bool is_directory(StringId64_t root,
                                       ^
../../../engine/src/cetech/filesystem/private/filesystem.cc:269:35: warning: unused parameter 'root'
      [-Wunused-parameter]
        bool is_file(StringId64_t root,
                                  ^
../../../engine/src/cetech/filesystem/private/filesystem.cc:286:44: warning: unused parameter 'root'
      [-Wunused-parameter]
        void delete_directory(StringId64_t root,
                                           ^
../../../engine/src/cetech/filesystem/private/filesystem.cc:303:39: warning: unused parameter 'root'
      [-Wunused-parameter]
        void create_file(StringId64_t root,
                                      ^
../../../engine/src/cetech/filesystem/private/filesystem.cc:308:39: warning: unused parameter 'root'
      [-Wunused-parameter]
        void delete_file(StringId64_t root,
                                      ^
In file included from ../../../engine/src/cetech/develop/private/develop_manager.cc:6:
In file included from ../../../engine/src/cetech/develop/develop_manager.h:6:
../../../external/.build/darwin64/include/rapidjson/document.h:1065:22: fatal error: call to constructor of
      'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' is
      ambiguous
        GenericValue v(value);
                     ^ ~~~~~
../../../external/.build/darwin64/include/rapidjson/document.h:1136:16: note: in instantiation of function template
      specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<long>' requested here
        return AddMember(n, value, allocator);
               ^
../../../engine/src/cetech/develop/private/develop_manager.cc:228:22: note: in instantiation of function template
      specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<long>' requested here
            document.AddMember("time", time::get_sec(e->time), document.GetAllocator());
                     ^
../../../external/.build/darwin64/include/rapidjson/document.h:510:14: note: candidate constructor
    explicit GenericValue(int i) RAPIDJSON_NOEXCEPT : data_(), flags_(kNumberIntFlag) {
             ^
../../../external/.build/darwin64/include/rapidjson/document.h:517:14: note: candidate constructor
    explicit GenericValue(unsigned u) RAPIDJSON_NOEXCEPT : data_(), flags_(kNumberUintFlag) {
             ^
../../../external/.build/darwin64/include/rapidjson/document.h:524:14: note: candidate constructor
    explicit GenericValue(int64_t i64) RAPIDJSON_NOEXCEPT : data_(), flags_(kNumberInt64Flag) {
             ^
../../../external/.build/darwin64/include/rapidjson/document.h:538:14: note: candidate constructor
    explicit GenericValue(uint64_t u64) RAPIDJSON_NOEXCEPT : data_(), flags_(kNumberUint64Flag) {
             ^
../../../external/.build/darwin64/include/rapidjson/document.h:549:14: note: candidate constructor
    explicit GenericValue(double d) RAPIDJSON_NOEXCEPT : data_(), flags_(kNumberDoubleFlag) { data_.n.d = d; }
             ^
3 warnings and 1 error generated.
make[1]: *** [../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/develop/private/develop_manager.o] Error 1
make[1]: *** Waiting for unfinished jobs....
6 warnings generated.
make: *** [cetech1] Error 2
Traceback (most recent call last):
  File "make.py", line 174, in <module>
    main()
  File "make.py", line 163, in main
    make(args.config, args.platform, args.generate)
  File "make.py", line 144, in make
    subprocess.check_call(PLATFORMS_BUILD[platform][config])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', '-R', '-C', '.build/projects/gmake-osx', 'config=debug64']' returned non-zero exit status 2
```

**Comment by lukleh** [comment]
```
Runing genie.
darwin64
Building configurations...
Running action 'gmake'...
Generating ../.build/projects/gmake-osx/Makefile...
Generating ../.build/projects/gmake-osx/celib_static.make...
Generating ../.build/projects/gmake-osx/cetech1.make...
Done.
Building.
==== Building celib_static (debug64) ====
==== Building cetech1 (debug64) ====
renderer.cc
resource_compiler.cc
task_manager.cc
thread.cc
../../../engine/src/cetech/task_manager/private/task_manager.cc:110:13: fatal error: unknown type name 'cpu_set_t'
            cpu_set_t cpuset;
            ^
../../../engine/src/cetech/resource_compiler/private/resource_compiler.cc:193:18: fatal error: unknown type name
      'ulong'
            for (ulong i = 0; i < sizeof(in_dirs) / sizeof(StringId64_t); ++i) {
                 ^
1 error generated.
1 error generated.
make[1]: *** [../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/task_manager/private/task_manager.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/resource_compiler/private/resource_compiler.o] Error 1
window.cc
make: *** [cetech1] Error 2
Traceback (most recent call last):
  File "make.py", line 174, in <module>
    main()
  File "make.py", line 163, in main
    make(args.config, args.platform, args.generate)
  File "make.py", line 144, in make
    subprocess.check_call(PLATFORMS_BUILD[platform][config])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', '-R', '-C', '.build/projects/gmake-osx', 'config=debug64']' returned non-zero exit status 2
```

**Comment by lukleh** [comment]
```
Runing genie.
darwin64
Building configurations...
Running action 'gmake'...
Generating ../.build/projects/gmake-osx/Makefile...
Generating ../.build/projects/gmake-osx/celib_static.make...
Generating ../.build/projects/gmake-osx/cetech1.make...
Done.
Building.
==== Building celib_static (debug64) ====
==== Building cetech1 (debug64) ====
Linking cetech1
Undefined symbols for architecture x86_64:
  "_AudioObjectAddPropertyListener", referenced from:
      _COREAUDIO_Init in libSDL2.a(SDL_coreaudio.o)
      _COREAUDIO_OpenDevice in libSDL2.a(SDL_coreaudio.o)
  "_AudioObjectGetPropertyData", referenced from:
      _COREAUDIO_OpenDevice in libSDL2.a(SDL_coreaudio.o)
      _device_unplugged in libSDL2.a(SDL_coreaudio.o)
      _build_device_list in libSDL2.a(SDL_coreaudio.o)
  "_AudioObjectGetPropertyDataSize", referenced from:
      _build_device_list in libSDL2.a(SDL_coreaudio.o)
  "_AudioObjectRemovePropertyListener", referenced from:
      _COREAUDIO_CloseDevice in libSDL2.a(SDL_coreaudio.o)
      _COREAUDIO_Deinitialize in libSDL2.a(SDL_coreaudio.o)
  "_AudioOutputUnitStart", referenced from:
      _COREAUDIO_OpenDevice in libSDL2.a(SDL_coreaudio.o)
  "_AudioOutputUnitStop", referenced from:
      _COREAUDIO_CloseDevice in libSDL2.a(SDL_coreaudio.o)
  "_AudioUnitInitialize", referenced from:
      _COREAUDIO_OpenDevice in libSDL2.a(SDL_coreaudio.o)
  "_AudioUnitSetProperty", referenced from:
      _COREAUDIO_OpenDevice in libSDL2.a(SDL_coreaudio.o)
      _COREAUDIO_CloseDevice in libSDL2.a(SDL_coreaudio.o)
  "_FFCreateDevice", referenced from:
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceCreateEffect", referenced from:
      _SDL_SYS_HapticNewEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceGetForceFeedbackCapabilities", referenced from:
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceGetForceFeedbackProperty", referenced from:
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceReleaseEffect", referenced from:
      _SDL_SYS_HapticDestroyEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceSendForceFeedbackCommand", referenced from:
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticPause in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticUnpause in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticStopAll in libSDL2.a(SDL_syshaptic.o)
  "_FFDeviceSetForceFeedbackProperty", referenced from:
      _SDL_SYS_HapticSetGain in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticSetAutocenter in libSDL2.a(SDL_syshaptic.o)
  "_FFEffectGetEffectStatus", referenced from:
      _SDL_SYS_HapticGetEffectStatus in libSDL2.a(SDL_syshaptic.o)
  "_FFEffectSetParameters", referenced from:
      _SDL_SYS_HapticUpdateEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFEffectStart", referenced from:
      _SDL_SYS_HapticRunEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFEffectStop", referenced from:
      _SDL_SYS_HapticStopEffect in libSDL2.a(SDL_syshaptic.o)
  "_FFIsForceFeedback", referenced from:
      _JoystickDeviceWasAddedCallback in libSDL2.a(SDL_sysjoystick.o)
      _MacHaptic_MaybeAddDevice in libSDL2.a(SDL_syshaptic.o)
  "_FFReleaseDevice", referenced from:
      _SDL_SYS_HapticOpenFromService in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticClose in libSDL2.a(SDL_syshaptic.o)
  "_IODisplayCreateInfoDictionary", referenced from:
      _Cocoa_InitModes in libSDL2.a(SDL_cocoamodes.o)
  "_IOHIDDeviceCopyMatchingElements", referenced from:
      _JoystickDeviceWasAddedCallback in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDDeviceGetProperty", referenced from:
      _JoystickDeviceWasAddedCallback in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDDeviceGetService", referenced from:
      _JoystickDeviceWasAddedCallback in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDDeviceGetValue", referenced from:
      _SDL_SYS_JoystickUpdate in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDDeviceRegisterRemovalCallback", referenced from:
      _JoystickDeviceWasAddedCallback in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDDeviceScheduleWithRunLoop", referenced from:
      _JoystickDeviceWasAddedCallback in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDDeviceUnscheduleFromRunLoop", referenced from:
      _FreeDevice in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDElementGetChildren", referenced from:
      _AddHIDElement in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDElementGetCookie", referenced from:
      _AddHIDElement in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDElementGetLogicalMax", referenced from:
      _AddHIDElement in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDElementGetLogicalMin", referenced from:
      _AddHIDElement in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDElementGetType", referenced from:
      _AddHIDElement in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDElementGetTypeID", referenced from:
      _AddHIDElement in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDElementGetUsage", referenced from:
      _AddHIDElement in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDElementGetUsagePage", referenced from:
      _AddHIDElement in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDManagerClose", referenced from:
      _SDL_SYS_JoystickQuit in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDManagerCreate", referenced from:
      _SDL_SYS_JoystickInit in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDManagerOpen", referenced from:
      _SDL_SYS_JoystickInit in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDManagerRegisterDeviceMatchingCallback", referenced from:
      _SDL_SYS_JoystickInit in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDManagerScheduleWithRunLoop", referenced from:
      _SDL_SYS_JoystickInit in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDManagerSetDeviceMatchingMultiple", referenced from:
      _SDL_SYS_JoystickInit in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDManagerUnscheduleFromRunLoop", referenced from:
      _SDL_SYS_JoystickQuit in libSDL2.a(SDL_sysjoystick.o)
  "_IOHIDValueGetIntegerValue", referenced from:
      _SDL_SYS_JoystickUpdate in libSDL2.a(SDL_sysjoystick.o)
  "_IOIteratorIsValid", referenced from:
      _SDL_SYS_HapticInit in libSDL2.a(SDL_syshaptic.o)
  "_IOIteratorNext", referenced from:
      _SDL_SYS_HapticInit in libSDL2.a(SDL_syshaptic.o)
  "_IOObjectIsEqualTo", referenced from:
      _MacHaptic_MaybeAddDevice in libSDL2.a(SDL_syshaptic.o)
      _MacHaptic_MaybeRemoveDevice in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_JoystickSameHaptic in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticOpenFromJoystick in libSDL2.a(SDL_syshaptic.o)
  "_IOObjectRelease", referenced from:
      _SDL_SYS_HapticInit in libSDL2.a(SDL_syshaptic.o)
      _MacHaptic_MaybeAddDevice in libSDL2.a(SDL_syshaptic.o)
      _MacHaptic_MaybeRemoveDevice in libSDL2.a(SDL_syshaptic.o)
      _SDL_SYS_HapticQuit in libSDL2.a(SDL_syshaptic.o)
  "_IOObjectRetain", referenced from:
      _MacHaptic_MaybeAddDevice in libSDL2.a(SDL_syshaptic.o)
  "_IOPMAssertionCreateWithDescription", referenced from:
      _Cocoa_SuspendScreenSaver in libSDL2.a(SDL_cocoaevents.o)
  "_IOPMAssertionRelease", referenced from:
      _Cocoa_SuspendScreenSaver in libSDL2.a(SDL_cocoaevents.o)
  "_IOPSCopyPowerSourcesInfo", referenced from:
      _SDL_GetPowerInfo_MacOSX in libSDL2.a(SDL_syspower.o)
  "_IOPSCopyPowerSourcesList", referenced from:
      _SDL_GetPowerInfo_MacOSX in libSDL2.a(SDL_syspower.o)
  "_IOPSGetPowerSourceDescription", referenced from:
      _SDL_GetPowerInfo_MacOSX in libSDL2.a(SDL_syspower.o)
  "_IORegistryEntryCreateCFProperties", referenced from:
      _MacHaptic_MaybeAddDevice in libSDL2.a(SDL_syshaptic.o)
  "_IORegistryEntryGetParentEntry", referenced from:
      _MacHaptic_MaybeAddDevice in libSDL2.a(SDL_syshaptic.o)
  "_IOServiceGetMatchingServices", referenced from:
      _SDL_SYS_HapticInit in libSDL2.a(SDL_syshaptic.o)
  "_IOServiceMatching", referenced from:
      _SDL_SYS_HapticInit in libSDL2.a(SDL_syshaptic.o)
  "_KBGetLayoutType", referenced from:
      _Cocoa_HandleKeyEvent in libSDL2.a(SDL_cocoakeyboard.o)
  "_LMGetKbdType", referenced from:
      _UpdateKeymap in libSDL2.a(SDL_cocoakeyboard.o)
      _Cocoa_HandleKeyEvent in libSDL2.a(SDL_cocoakeyboard.o)
  "_TISCopyCurrentKeyboardLayoutInputSource", referenced from:
      _UpdateKeymap in libSDL2.a(SDL_cocoakeyboard.o)
  "_TISGetInputSourceProperty", referenced from:
      _UpdateKeymap in libSDL2.a(SDL_cocoakeyboard.o)
  "_iconv", referenced from:
      _SDL_iconv_REAL in libSDL2.a(SDL_iconv.o)
      _SDL_iconv_string_REAL in libSDL2.a(SDL_iconv.o)
     (maybe you meant: _SDL_iconv_REAL, _SDL_iconv_open , _SDL_iconv_open_REAL , _SDL_iconv_string , _SDL_iconv , _SDL_iconv_string_REAL , _SDL_iconv_close , _SDL_iconv_close_REAL )
  "_iconv_close", referenced from:
      _SDL_iconv_close_REAL in libSDL2.a(SDL_iconv.o)
      _SDL_iconv_string_REAL in libSDL2.a(SDL_iconv.o)
     (maybe you meant: _SDL_iconv_close, _SDL_iconv_close_REAL )
  "_iconv_open", referenced from:
      _SDL_iconv_open_REAL in libSDL2.a(SDL_iconv.o)
      _SDL_iconv_string_REAL in libSDL2.a(SDL_iconv.o)
     (maybe you meant: _SDL_iconv_open, _SDL_iconv_open_REAL )
  "_kIOMasterPortDefault", referenced from:
      _SDL_SYS_HapticInit in libSDL2.a(SDL_syshaptic.o)
  "_kTISPropertyUnicodeKeyLayoutData", referenced from:
      _UpdateKeymap in libSDL2.a(SDL_cocoakeyboard.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../../osx64_clang/bin/cetech1Debug] Error 1
make: *** [cetech1] Error 2
Traceback (most recent call last):
  File "make.py", line 174, in <module>
    main()
  File "make.py", line 163, in main
    make(args.config, args.platform, args.generate)
  File "make.py", line 144, in make
    subprocess.check_call(PLATFORMS_BUILD[platform][config])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', '-R', '-C', '.build/projects/gmake-osx', 'config=debug64']' returned non-zero exit status 2
```

**Comment by lukleh** [comment]
```
Runing genie.
darwin64
Building configurations...
Running action 'gmake'...
Generating ../.build/projects/gmake-osx/Makefile...
Generating ../.build/projects/gmake-osx/celib_static.make...
Generating ../.build/projects/gmake-osx/cetech1.make...
Done.
Building.
==== Building celib_static (debug64) ====
==== Building cetech1 (debug64) ====
Linking cetech1
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/application/private/application.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/develop/private/console_server.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/develop/private/develop_manager.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/input/private/keyboard.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/input/private/mouse.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/log/private/handlers.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/lua/lua_enviroment.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/lua/lua_resources.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/package_manager/private/package_manager.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/renderer/private/renderer.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/resource_compiler/private/resource_compiler.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/resource_manager/private/resource_manager.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/task_manager/private/task_manager.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/thread/private/thread.o
duplicate symbol __Z13clock_gettimeiP8timespec in:
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/main.o
    ../../osx64_clang/obj/x64/Debug/cetech1/engine/src/cetech/window/private/window.o
ld: 15 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../../osx64_clang/bin/cetech1Debug] Error 1
make: *** [cetech1] Error 2
Traceback (most recent call last):
  File "make.py", line 174, in <module>
    main()
  File "make.py", line 163, in main
    make(args.config, args.platform, args.generate)
  File "make.py", line 144, in make
    subprocess.check_call(PLATFORMS_BUILD[platform][config])
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', '-R', '-C', '.build/projects/gmake-osx', 'config=debug64']' returned non-zero exit status 2
```
